$NAMES=[
{},
{:id => "jean-marie-binetruy",:name => "Jean-Marie Binetruy"},
{:id => "michel-raison",:name => "Michel Raison"},
{:id => "cecile-gallez",:name => "Cécile Gallez"},
{},
{:id => "christian-patria",:name => "Christian Patria"},
{:id => "jean-paul-garraud",:name => "Jean-Paul Garraud"},
{:id => "jean-francois-chossy",:name => "Jean-François Chossy"},
{:id => "francoise-branget",:name => "Françoise Branget"},
{:id => "pierre-lang",:name => "Pierre Lang"},
{:id => "bernard-debre",:name => "Bernard Debré"},
{:id => "philippe-armand-martin",:name => "Philippe Armand Martin"},
{:id => "bernard-reynes",:name => "Bernard Reynès"},
{:id => "patrick-labaune",:name => "Patrick Labaune"},
{:id => "gabriel-biancheri",:name => "Gabriel Biancheri"},
{:id => "etienne-mourrut",:name => "Étienne Mourrut"},
{:id => "didier-julia",:name => "Didier Julia"},
{:id => "jean-yves-bony",:name => "Jean-Yves Bony"},
{:id => "franck-marlin",:name => "Franck Marlin"},
{:id => "jean-louis-christ",:name => "Jean-Louis Christ"},
{:id => "jacques-houssin",:name => "Jacques Houssin"},
{:id => "bernard-depierre",:name => "Bernard Depierre"},
{:id => "sylvia-bassot",:name => "Sylvia Bassot"},
{:id => "gerard-menuel",:name => "Gérard Menuel"},
{:id => "jean-claude-bouchet",:name => "Jean-Claude Bouchet"},
{:id => "edwige-antier",:name => "Edwige Antier"},
{:id => "jean-claude-beaulieu",:name => "Jean-Claude Beaulieu"},
{:id => "jean-claude-mignon",:name => "Jean-Claude Mignon"},
{:id => "michel-voisin",:name => "Michel Voisin"},
{},
{:id => "alain-marc",:name => "Alain Marc"},
{:id => "patrice-calmejane",:name => "Patrice Calméjane"},
{:id => "gerard-lorgeoux",:name => "Gérard Lorgeoux"},
{:id => "camille-de-rocca-serra",:name => "Camille de Rocca Serra"},
{},
{:id => "jean-pierre-decool",:name => "Jean-Pierre Decool"},
{:id => "marie-jo-zimmermann",:name => "Marie-Jo Zimmermann"},
{},
{:id => "jacques-lamblin",:name => "Jacques Lamblin"},
{:id => "marie-christine-dalloz",:name => "Marie-Christine Dalloz"},
{:id => "charles-de-la-verpilliere",:name => "Charles de La Verpillière"},
{:id => "edouard-courtial",:name => "Édouard Courtial"},
{},
{:id => "alain-moyne-bressand",:name => "Alain Moyne-Bressand"},
{:id => "gerard-voisin",:name => "Gérard Voisin"},
{:id => "etienne-blanc",:name => "Étienne Blanc"},
{},
{:id => "jean-frederic-poisson",:name => "Jean-Frédéric Poisson"},
{:id => "jacques-grosperrin",:name => "Jacques Grosperrin"},
{:id => "vincent-descoeur",:name => "Vincent Descoeur"},
{:id => "xavier-breton",:name => "Xavier Breton"},
{:id => "christian-menard",:name => "Christian Ménard"},
{:id => "lucien-degauchy",:name => "Lucien Degauchy"},
{:id => "christian-vanneste",:name => "Christian Vanneste"},
{:id => "marc-le-fur",:name => "Marc Le Fur"},
{},
{:id => "jean-pierre-marcon",:name => "Jean-Pierre Marcon"},
{:id => "andre-wojciechowski",:name => "André Wojciechowski"},
{:id => "jean-philippe-maurer",:name => "Jean-Philippe Maurer"},
{:id => "michel-lezeau",:name => "Michel Lezeau"},
{:id => "jean-auclair",:name => "Jean Auclair"},
{},
{:id => "daniel-fasquelle",:name => "Daniel Fasquelle"},
{:id => "olivier-carre",:name => "Olivier Carré"},
{:id => "david-douillet",:name => "David Douillet"},
{},
{:id => "veronique-besse",:name => "Véronique Besse"},
{:id => "francois-xavier-villain",:name => "François-Xavier Villain"},
{:id => "nicolas-dupont-aignan",:name => "Nicolas Dupont-Aignan"},
{},
{:id => "francois-bayrou",:name => "François Bayrou"},
{:id => "jean-lassalle",:name => "Jean Lassalle"},
{:id => "dominique-souchet",:name => "Dominique Souchet"},
{:id => "abdoulatifou-aly",:name => "Abdoulatifou Aly"},
{},
{:id => "jean-pierre-grand",:name => "Jean-Pierre Grand"},
{:id => "richard-mallie",:name => "Richard Mallié"},
{:id => "bernard-accoyer",:name => "Bernard Accoyer"},
{:id => "herve-mariton",:name => "Hervé Mariton"},
{:id => "yves-censi",:name => "Yves Censi"},
{:id => "jean-roatta",:name => "Jean Roatta"},
{:id => "jean-tiberi",:name => "Jean Tiberi"},
{:id => "catherine-vautrin",:name => "Catherine Vautrin"},
{:id => "dominique-perben",:name => "Dominique Perben"},
{:id => "jacques-pelissard",:name => "Jacques Pélissard"},
{:id => "daniel-poulou",:name => "Daniel Poulou"},
{:id => "marie-anne-montchamp",:name => "Marie-Anne Montchamp"},
{:id => "nicole-ameline",:name => "Nicole Ameline"},
{:id => "xavier-bertrand",:name => "Xavier Bertrand"},
{:id => "georges-mothron",:name => "Georges Mothron"},
{:id => "christian-jacob",:name => "Christian Jacob"},
{:id => "jacques-kossowski",:name => "Jacques Kossowski"},
{:id => "berengere-poletti",:name => "Bérengère Poletti"},
{:id => "thierry-mariani",:name => "Thierry Mariani"},
{:id => "francois-cornut-gentille",:name => "François Cornut-Gentille"},
{:id => "jerome-chartier",:name => "Jérôme Chartier"},
{:id => "renaud-muselier",:name => "Renaud Muselier"},
{:id => "philippe-briand",:name => "Philippe Briand"},
{:id => "michele-tabarot",:name => "Michèle Tabarot"},
{:id => "jean-francois-cope",:name => "Jean-François Copé"},
{:id => "yves-deniaud",:name => "Yves Deniaud"},
{:id => "jean-francois-lamour",:name => "Jean-François Lamour"},
{:id => "jean-pierre-giran",:name => "Jean-Pierre Giran"},
{:id => "bernard-brochand",:name => "Bernard Brochand"},
{:id => "chantal-brunel",:name => "Chantal Brunel"},
{:id => "jean-michel-ferrand",:name => "Jean-Michel Ferrand"},
{:id => "jerome-bignon",:name => "Jérôme Bignon"},
{},
{:id => "michel-terrot",:name => "Michel Terrot"},
{:id => "jean-marc-lefranc",:name => "Jean-Marc Lefranc"},
{:id => "michel-buillard",:name => "Michel Buillard"},
{:id => "rene-paul-victoria",:name => "René-Paul Victoria"},
{:id => "roland-blum",:name => "Roland Blum"},
{:id => "jean-yves-besselat",:name => "Jean-Yves Besselat"},
{:id => "jean-pierre-dupont",:name => "Jean-Pierre Dupont"},
{},
{:id => "daniel-spagnou",:name => "Daniel Spagnou"},
{:id => "jean-jacques-gaultier",:name => "Jean-Jacques Gaultier"},
{:id => "michel-heinrich",:name => "Michel Heinrich"},
{:id => "gerard-cherpion",:name => "Gérard Cherpion"},
{:id => "jacques-le-guen",:name => "Jacques Le Guen"},
{},
{:id => "guy-malherbe",:name => "Guy Malherbe"},
{:id => "alfred-almont",:name => "Alfred Almont"},
{:id => "gilles-d-ettore",:name => "Gilles d'Ettore"},
{:id => "patrice-martin-lalande",:name => "Patrice Martin-Lalande"},
{:id => "marc-francina",:name => "Marc Francina"},
{:id => "gabrielle-louis-carabin",:name => "Gabrielle Louis-Carabin"},
{:id => "michel-diefenbacher",:name => "Michel Diefenbacher"},
{:id => "marguerite-lamour",:name => "Marguerite Lamour"},
{:id => "jacques-domergue",:name => "Jacques Domergue"},
{},
{:id => "eric-ciotti",:name => "Éric Ciotti"},
{:id => "franck-gilard",:name => "Franck Gilard"},
{:id => "elie-aboud",:name => "Élie Aboud"},
{:id => "denis-jacquat",:name => "Denis Jacquat"},
{:id => "andre-flajolet",:name => "André Flajolet"},
{:id => "pierre-morel-a-l-huissier",:name => "Pierre Morel-A-L'Huissier"},
{:id => "charles-ange-ginesy",:name => "Charles-Ange Ginesy"},
{:id => "philippe-meunier",:name => "Philippe Meunier"},
{:id => "max-roustan",:name => "Max Roustan"},
{:id => "daniel-fidelin",:name => "Daniel Fidelin"},
{},
{:id => "michel-grall",:name => "Michel Grall"},
{:id => "valerie-rosso-debord",:name => "Valérie Rosso-Debord"},
{:id => "fernand-sire",:name => "Fernand Siré"},
{:id => "francois-calvet",:name => "François Calvet"},
{:id => "daniel-mach",:name => "Daniel Mach"},
{:id => "daniel-garrigue",:name => "Daniel Garrigue"},
{:id => "guenhael-huet",:name => "Guénhaël Huet"},
{:id => "philippe-gosselin",:name => "Philippe Gosselin"},
{:id => "christine-marin",:name => "Christine Marin"},
{:id => "didier-gonzales",:name => "Didier Gonzales"},
{:id => "francoise-guegot",:name => "Françoise Guégot"},
{:id => "michel-havard",:name => "Michel Havard"},
{:id => "marianne-dubois",:name => "Marianne Dubois"},
{:id => "philippe-morenvillier",:name => "Philippe Morenvillier"},
{:id => "lionel-tardy",:name => "Lionel Tardy"},
{:id => "jacqueline-irles",:name => "Jacqueline Irles"},
{},
{},
{},
{:id => "francois-loos",:name => "François Loos"},
{:id => "antoine-herth",:name => "Antoine Herth"},
{:id => "andre-schneider",:name => "André Schneider"},
{:id => "jean-jacques-guillet",:name => "Jean-Jacques Guillet"},
{:id => "jean-luc-reitzer",:name => "Jean-Luc Reitzer"},
{:id => "jean-ueberschlag",:name => "Jean Ueberschlag"},
{:id => "guy-teissier",:name => "Guy Teissier"},
{:id => "pierre-cardo",:name => "Pierre Cardo"},
{:id => "herve-gaymard",:name => "Hervé Gaymard"},
{:id => "jean-michel-couve",:name => "Jean-Michel Couve"},
{:id => "claude-goasguen",:name => "Claude Goasguen"},
{:id => "rene-couanau",:name => "René Couanau"},
{:id => "francois-baroin",:name => "François Baroin"},
{:id => "alain-cousin",:name => "Alain Cousin"},
{:id => "gilles-carrez",:name => "Gilles Carrez"},
{:id => "francoise-de-panafieu",:name => "Françoise de Panafieu"},
{:id => "yves-bur",:name => "Yves Bur"},
{:id => "jean-luc-warsmann",:name => "Jean-Luc Warsmann"},
{:id => "patrick-ollier",:name => "Patrick Ollier"},
{:id => "jean-leonetti",:name => "Jean Leonetti"},
{:id => "martine-aurillac",:name => "Martine Aurillac"},
{:id => "christian-kert",:name => "Christian Kert"},
{:id => "yves-jego",:name => "Yves Jego"},
{:id => "michel-bouvard",:name => "Michel Bouvard"},
{:id => "pierre-mehaignerie",:name => "Pierre Méhaignerie"},
{:id => "jean-claude-guibal",:name => "Jean-Claude Guibal"},
{:id => "brigitte-bareges",:name => "Brigitte Barèges"},
{:id => "jean-pierre-soisson",:name => "Jean-Pierre Soisson"},
{:id => "serge-grouard",:name => "Serge Grouard"},
{:id => "jean-louis-bernard",:name => "Jean-Louis Bernard"},
{:id => "marie-josee-roig",:name => "Marie-Josée Roig"},
{:id => "emile-blessig",:name => "Émile Blessig"},
{},
{:id => "jean-paul-anciaux",:name => "Jean-Paul Anciaux"},
{:id => "dino-cinieri",:name => "Dino Cinieri"},
{:id => "chantal-bourrague",:name => "Chantal Bourragué"},
{:id => "guy-geoffroy",:name => "Guy Geoffroy"},
{:id => "henriette-martinez",:name => "Henriette Martinez"},
{:id => "sebastien-huyghe",:name => "Sébastien Huyghe"},
{:id => "patrick-beaudouin",:name => "Patrick Beaudouin"},
{},
{:id => "bernard-perrut",:name => "Bernard Perrut"},
{:id => "manuel-aeschlimann",:name => "Manuel Aeschlimann"},
{:id => "dominique-le-mener",:name => "Dominique Le Mèner"},
{:id => "jean-louis-leonard",:name => "Jean-Louis Léonard"},
{:id => "muriel-marland-militello",:name => "Muriel Marland-Militello"},
{},
{:id => "guy-lefrand",:name => "Guy Lefrand"},
{:id => "genevieve-colot",:name => "Geneviève Colot"},
{:id => "michel-lejeune",:name => "Michel Lejeune"},
{:id => "robert-lecou",:name => "Robert Lecou"},
{:id => "louis-guedon",:name => "Louis Guédon"},
{:id => "michel-zumkeller",:name => "Michel Zumkeller"},
{:id => "francois-grosdidier",:name => "François Grosdidier"},
{:id => "frederic-reiss",:name => "Frédéric Reiss"},
{:id => "damien-meslot",:name => "Damien Meslot"},
{},
{:id => "beatrice-pavy",:name => "Béatrice Pavy"},
{:id => "jean-claude-mathis",:name => "Jean-Claude Mathis"},
{:id => "remi-delatte",:name => "Rémi Delatte"},
{:id => "celeste-lett",:name => "Céleste Lett"},
{:id => "valerie-boyer",:name => "Valérie Boyer"},
{:id => "franck-riester",:name => "Franck Riester"},
{:id => "yves-albarello",:name => "Yves Albarello"},
{:id => "cecile-dumoulin",:name => "Cécile Dumoulin"},
{:id => "francis-saint-leger",:name => "Francis Saint-Léger"},
{:id => "marcel-bonnot",:name => "Marcel Bonnot"},
{},
{:id => "marie-louise-fort",:name => "Marie-Louise Fort"},
{:id => "martial-saddier",:name => "Martial Saddier"},
{:id => "philippe-goujon",:name => "Philippe Goujon"},
{:id => "yves-vandewalle",:name => "Yves Vandewalle"},
{:id => "eric-diard",:name => "Éric Diard"},
{:id => "arnaud-robinet",:name => "Arnaud Robinet"},
{:id => "isabelle-vasseur",:name => "Isabelle Vasseur"},
{:id => "gael-yanno",:name => "Gaël Yanno"},
{:id => "anne-grommerch",:name => "Anne Grommerch"},
{:id => "nicolas-dhuicq",:name => "Nicolas Dhuicq"},
{:id => "gerard-gaudron",:name => "Gérard Gaudron"},
{:id => "franck-reynier",:name => "Franck Reynier"},
{:id => "didier-robert",:name => "Didier Robert"},
{:id => "jean-marie-morisset",:name => "Jean-Marie Morisset"},
{:id => "sauveur-gandolfi-scheit",:name => "Sauveur Gandolfi-Scheit"},
{:id => "dominique-tian",:name => "Dominique Tian"},
{},
{},
{:id => "pascal-clement",:name => "Pascal Clément"},
{:id => "yves-fromion",:name => "Yves Fromion"},
{:id => "loic-bouvard",:name => "Loïc Bouvard"},
{:id => "gerard-hamel",:name => "Gérard Hamel"},
{},
{:id => "bernard-deflesselles",:name => "Bernard Deflesselles"},
{:id => "marc-laffineur",:name => "Marc Laffineur"},
{:id => "francois-goulard",:name => "François Goulard"},
{:id => "jean-bardet",:name => "Jean Bardet"},
{:id => "jean-claude-lenoir",:name => "Jean-Claude Lenoir"},
{:id => "francois-michel-gonnot",:name => "François-Michel Gonnot"},
{:id => "michel-herbillon",:name => "Michel Herbillon"},
{:id => "alain-gest",:name => "Alain Gest"},
{:id => "claude-gatignol",:name => "Claude Gatignol"},
{:id => "serge-poignant",:name => "Serge Poignant"},
{:id => "claude-greff",:name => "Claude Greff"},
{:id => "dominique-dord",:name => "Dominique Dord"},
{:id => "yves-nicolin",:name => "Yves Nicolin"},
{:id => "francoise-hostalier",:name => "Françoise Hostalier"},
{:id => "didier-quentin",:name => "Didier Quentin"},
{:id => "eric-raoult",:name => "Éric Raoult"},
{:id => "pierre-lequiller",:name => "Pierre Lequiller"},
{:id => "claude-birraux",:name => "Claude Birraux"},
{:id => "philippe-cochet",:name => "Philippe Cochet"},
{:id => "alfred-trassy-paillogues",:name => "Alfred Trassy-Paillogues"},
{:id => "georges-tron",:name => "Georges Tron"},
{:id => "joelle-ceccaldi-raynaud",:name => "Joëlle Ceccaldi-Raynaud"},
{},
{:id => "lionnel-luca",:name => "Lionnel Luca"},
{:id => "pierre-frogier",:name => "Pierre Frogier"},
{:id => "marc-bernier",:name => "Marc Bernier"},
{:id => "jean-pierre-door",:name => "Jean-Pierre Door"},
{:id => "arnaud-richard",:name => "Arnaud Richard"},
{:id => "jean-pierre-nicolas",:name => "Jean-Pierre Nicolas"},
{:id => "arlette-grosskost",:name => "Arlette Grosskost"},
{},
{:id => "dominique-caillaud",:name => "Dominique Caillaud"},
{:id => "axel-poniatowski",:name => "Axel Poniatowski"},
{:id => "louis-giscard-d-estaing",:name => "Louis Giscard d'Estaing"},
{:id => "michel-piron",:name => "Michel Piron"},
{:id => "jacques-alain-benisti",:name => "Jacques Alain Bénisti"},
{},
{:id => "francois-scellier",:name => "François Scellier"},
{:id => "pierre-christophe-baguet",:name => "Pierre-Christophe Baguet"},
{:id => "jacques-myard",:name => "Jacques Myard"},
{:id => "jean-claude-flory",:name => "Jean-Claude Flory"},
{:id => "alain-suguenot",:name => "Alain Suguenot"},
{:id => "maryse-joissains-masini",:name => "Maryse Joissains-Masini"},
{:id => "louis-cosyns",:name => "Louis Cosyns"},
{:id => "alain-ferry",:name => "Alain Ferry"},
{:id => "bruno-bourg-broc",:name => "Bruno Bourg-Broc"},
{},
{:id => "jean-marie-rolland",:name => "Jean-Marie Rolland"},
{:id => "michel-sordi",:name => "Michel Sordi"},
{:id => "jean-marc-roubaud",:name => "Jean-Marc Roubaud"},
{:id => "georges-siffredi",:name => "Georges Siffredi"},
{:id => "christophe-priou",:name => "Christophe Priou"},
{:id => "yanick-paternotte",:name => "Yanick Paternotte"},
{:id => "gilles-bourdouleix",:name => "Gilles Bourdouleix"},
{:id => "sophie-delong",:name => "Sophie Delong"},
{:id => "eric-straumann",:name => "Éric Straumann"},
{:id => "jean-marie-sermier",:name => "Jean-Marie Sermier"},
{},
{:id => "jean-grenet",:name => "Jean Grenet"},
{:id => "genevieve-levy",:name => "Geneviève Levy"},
{:id => "georges-ginesta",:name => "Georges Ginesta"},
{:id => "josette-pons",:name => "Josette Pons"},
{:id => "jean-sebastien-vialatte",:name => "Jean-Sébastien Vialatte"},
{},
{:id => "alain-marty",:name => "Alain Marty"},
{:id => "claude-bodin",:name => "Claude Bodin"},
{:id => "philippe-boennec",:name => "Philippe Boënnec"},
{:id => "paul-jeanneteau",:name => "Paul Jeanneteau"},
{:id => "fabienne-labrette-menager",:name => "Fabienne Labrette-Ménager"},
{:id => "laure-de-la-raudiere",:name => "Laure de La Raudière"},
{:id => "bruno-sandras",:name => "Bruno Sandras"},
{:id => "bernard-gerard",:name => "Bernard Gérard"},
{:id => "patrice-verchere",:name => "Patrice Verchère"},
{:id => "bertrand-pancher",:name => "Bertrand Pancher"},
{:id => "philippe-vitel",:name => "Philippe Vitel"},
{},
{:id => "etienne-pinte",:name => "Étienne Pinte"},
{:id => "jean-claude-thomas",:name => "Jean-Claude Thomas"},
{:id => "jean-proriol",:name => "Jean Proriol"},
{:id => "pierre-morange",:name => "Pierre Morange"},
{:id => "pierre-lasbordes",:name => "Pierre Lasbordes"},
{:id => "thierry-lazaro",:name => "Thierry Lazaro"},
{:id => "jacques-le-nay",:name => "Jacques Le Nay"},
{:id => "jean-marc-nesme",:name => "Jean-Marc Nesme"},
{:id => "philippe-houillon",:name => "Philippe Houillon"},
{:id => "henri-plagnol",:name => "Henri Plagnol"},
{:id => "yannick-favennec",:name => "Yannick Favennec"},
{:id => "jean-pierre-gorges",:name => "Jean-Pierre Gorges"},
{:id => "francois-vannson",:name => "François Vannson"},
{:id => "olivier-dassault",:name => "Olivier Dassault"},
{:id => "jean-michel-fourgous",:name => "Jean-Michel Fourgous"},
{:id => "nicolas-forissier",:name => "Nicolas Forissier"},
{:id => "laurent-henart",:name => "Laurent Hénart"},
{:id => "marc-philippe-daubresse",:name => "Marc-Philippe Daubresse"},
{:id => "georges-colombier",:name => "Georges Colombier"},
{:id => "bernard-carayon",:name => "Bernard Carayon"},
{:id => "christophe-guilloteau",:name => "Christophe Guilloteau"},
{:id => "jean-charles-taugourdeau",:name => "Jean-Charles Taugourdeau"},
{:id => "francoise-briand",:name => "Françoise Briand"},
{:id => "philippe-nauche",:name => "Philippe Nauche"},
{:id => "michel-vergnier",:name => "Michel Vergnier"},
{:id => "alain-vidalies",:name => "Alain Vidalies"},
{},
{:id => "jacques-remiller",:name => "Jacques Remiller"},
{:id => "richard-dell-agnola",:name => "Richard Dell'Agnola"},
{:id => "patrick-balkany",:name => "Patrick Balkany"},
{:id => "patrice-debray",:name => "Patrice Debray"},
{:id => "daniel-boisserie",:name => "Daniel Boisserie"},
{:id => "martine-carrillon-couvreur",:name => "Martine Carrillon-Couvreur"},
{:id => "jean-pierre-dufau",:name => "Jean-Pierre Dufau"},
{},
{:id => "francois-sauvadet",:name => "François Sauvadet"},
{:id => "andre-santini",:name => "André Santini"},
{:id => "rudy-salles",:name => "Rudy Salles"},
{:id => "jean-christophe-lagarde",:name => "Jean-Christophe Lagarde"},
{:id => "francois-rochebloine",:name => "François Rochebloine"},
{},
{:id => "francoise-de-salvador",:name => "Françoise De Salvador"},
{:id => "frederic-cuvillier",:name => "Frédéric Cuvillier"},
{:id => "jean-grellier",:name => "Jean Grellier"},
{:id => "delphine-batho",:name => "Delphine Batho"},
{:id => "herve-de-charette",:name => "Hervé de Charette"},
{:id => "nicolas-perruchot",:name => "Nicolas Perruchot"},
{:id => "charles-de-courson",:name => "Charles de Courson"},
{:id => "maurice-leroy",:name => "Maurice Leroy"},
{:id => "francis-vercamer",:name => "Francis Vercamer"},
{},
{:id => "marie-odile-bouille",:name => "Marie-Odile Bouillé"},
{:id => "olivier-dussopt",:name => "Olivier Dussopt"},
{:id => "pascale-got",:name => "Pascale Got"},
{:id => "michele-delaunay",:name => "Michèle Delaunay"},
{:id => "yvan-lachaud",:name => "Yvan Lachaud"},
{:id => "jean-pierre-abelin",:name => "Jean-Pierre Abelin"},
{:id => "michel-hunault",:name => "Michel Hunault"},
{:id => "stephane-demilly",:name => "Stéphane Demilly"},
{:id => "philippe-folliot",:name => "Philippe Folliot"},
{:id => "philippe-vigier",:name => "Philippe Vigier"},
{},
{:id => "marc-vampa",:name => "Marc Vampa"},
{:id => "raymond-durand",:name => "Raymond Durand"},
{:id => "jean-louis-gagnaire",:name => "Jean-Louis Gagnaire"},
{:id => "henri-jibrayel",:name => "Henri Jibrayel"},
{:id => "jean-patrick-gille",:name => "Jean-Patrick Gille"},
{},
{:id => "jean-dionis-du-sejour",:name => "Jean Dionis du Séjour"},
{:id => "jean-luc-preel",:name => "Jean-Luc Préel"},
{:id => "francis-hillmeyer",:name => "Francis Hillmeyer"},
{:id => "olivier-jarde",:name => "Olivier Jardé"},
{:id => "claude-leteurtre",:name => "Claude Leteurtre"},
{:id => "thierry-benoit",:name => "Thierry Benoit"},
{:id => "colette-le-moal",:name => "Colette Le Moal"},
{:id => "francois-deluga",:name => "François Deluga"},
{:id => "christophe-sirugue",:name => "Christophe Sirugue"},
{:id => "marc-goua",:name => "Marc Goua"},
{:id => "daniel-goldberg",:name => "Daniel Goldberg"},
{},
{:id => "serge-letchimy",:name => "Serge Letchimy"},
{:id => "martine-lignieres-cassou",:name => "Martine Lignières-Cassou"},
{:id => "jean-paul-bacquet",:name => "Jean-Paul Bacquet"},
{:id => "elisabeth-guigou",:name => "Élisabeth Guigou"},
{:id => "marie-francoise-clergeau",:name => "Marie-Françoise Clergeau"},
{:id => "pascal-terrasse",:name => "Pascal Terrasse"},
{:id => "jean-louis-bianco",:name => "Jean-Louis Bianco"},
{:id => "julien-dray",:name => "Julien Dray"},
{:id => "michel-vauzelle",:name => "Michel Vauzelle"},
{:id => "alain-rousset",:name => "Alain Rousset"},
{:id => "jack-lang",:name => "Jack Lang"},
{:id => "tony-dreyfus",:name => "Tony Dreyfus"},
{:id => "bruno-le-roux",:name => "Bruno Le Roux"},
{:id => "daniele-hoffman-rispal",:name => "Danièle Hoffman-Rispal"},
{:id => "gaetan-gorce",:name => "Gaëtan Gorce"},
{:id => "patricia-adam",:name => "Patricia Adam"},
{:id => "manuel-valls",:name => "Manuel Valls"},
{:id => "alain-claeys",:name => "Alain Claeys"},
{:id => "daniel-vaillant",:name => "Daniel Vaillant"},
{:id => "marie-francoise-perol-dumont",:name => "Marie-Françoise Pérol-Dumont"},
{:id => "sandrine-mazetier",:name => "Sandrine Mazetier"},
{:id => "pierre-moscovici",:name => "Pierre Moscovici"},
{:id => "jean-christophe-cambadelis",:name => "Jean-Christophe Cambadélis"},
{:id => "marisol-touraine",:name => "Marisol Touraine"},
{:id => "jean-marie-le-guen",:name => "Jean-Marie Le Guen"},
{:id => "christian-bataille",:name => "Christian Bataille"},
{},
{:id => "marie-renee-oget",:name => "Marie-Renée Oget"},
{:id => "gerard-bapt",:name => "Gérard Bapt"},
{:id => "jean-pierre-balligand",:name => "Jean-Pierre Balligand"},
{:id => "philippe-duron",:name => "Philippe Duron"},
{:id => "francois-pupponi",:name => "François Pupponi"},
{:id => "danielle-bousquet",:name => "Danielle Bousquet"},
{:id => "serge-janquin",:name => "Serge Janquin"},
{},
{:id => "germinal-peiro",:name => "Germinal Peiro"},
{:id => "jean-michel",:name => "Jean Michel"},
{:id => "david-habib",:name => "David Habib"},
{:id => "jean-yves-le-deaut",:name => "Jean-Yves Le Déaut"},
{:id => "christophe-caresche",:name => "Christophe Caresche"},
{},
{:id => "annick-lepetit",:name => "Annick Lepetit"},
{:id => "george-pau-langevin",:name => "George Pau-Langevin"},
{:id => "jean-yves-le-bouillonnec",:name => "Jean-Yves Le Bouillonnec"},
{:id => "patrick-bloche",:name => "Patrick Bloche"},
{:id => "jacques-bascou",:name => "Jacques Bascou"},
{:id => "jean-paul-dupre",:name => "Jean-Paul Dupré"},
{:id => "maxime-bono",:name => "Maxime Bono"},
{:id => "michel-francaix",:name => "Michel Françaix"},
{:id => "thierry-carcenac",:name => "Thierry Carcenac"},
{},
{:id => "claude-darciaux",:name => "Claude Darciaux"},
{:id => "jean-paul-chanteguet",:name => "Jean-Paul Chanteguet"},
{:id => "andre-vezinhet",:name => "André Vézinhet"},
{:id => "monique-iborra",:name => "Monique Iborra"},
{:id => "simon-renucci",:name => "Simon Renucci"},
{:id => "william-dumas",:name => "William Dumas"},
{:id => "louis-joseph-manscour",:name => "Louis-Joseph Manscour"},
{:id => "rene-rouquet",:name => "René Rouquet"},
{:id => "eric-jalton",:name => "Éric Jalton"},
{:id => "jean-launay",:name => "Jean Launay"},
{},
{:id => "jean-gaubert",:name => "Jean Gaubert"},
{:id => "armand-jung",:name => "Armand Jung"},
{:id => "kleber-mesquida",:name => "Kléber Mesquida"},
{:id => "pierre-forgues",:name => "Pierre Forgues"},
{:id => "yves-durand",:name => "Yves Durand"},
{},
{},
{:id => "gilbert-mathon",:name => "Gilbert Mathon"},
{:id => "marcel-rogemont",:name => "Marcel Rogemont"},
{:id => "dominique-raimbourg",:name => "Dominique Raimbourg"},
{:id => "marie-line-reynaud",:name => "Marie-Line Reynaud"},
{:id => "catherine-quere",:name => "Catherine Quéré"},
{:id => "michel-issindou",:name => "Michel Issindou"},
{:id => "jean-rene-marsac",:name => "Jean-René Marsac"},
{:id => "annick-le-loch",:name => "Annick Le Loch"},
{:id => "jean-jacques-urvoas",:name => "Jean-Jacques Urvoas"},
{:id => "bernard-lesterlin",:name => "Bernard Lesterlin"},
{:id => "jean-mallot",:name => "Jean Mallot"},
{},
{},
{},
{},
{},
{:id => "francoise-olivier-coupeau",:name => "Françoise Olivier-Coupeau"},
{:id => "jean-glavany",:name => "Jean Glavany"},
{:id => "catherine-genisson",:name => "Catherine Génisson"},
{:id => "francois-lamy",:name => "François Lamy"},
{:id => "andre-vallini",:name => "André Vallini"},
{:id => "michel-pajon",:name => "Michel Pajon"},
{:id => "marylise-lebranchu",:name => "Marylise Lebranchu"},
{:id => "henri-emmanuelli",:name => "Henri Emmanuelli"},
{:id => "christian-paul",:name => "Christian Paul"},
{:id => "arnaud-montebourg",:name => "Arnaud Montebourg"},
{:id => "jean-jack-queyranne",:name => "Jean-Jack Queyranne"},
{:id => "victorin-lurel",:name => "Victorin Lurel"},
{:id => "michel-sapin",:name => "Michel Sapin"},
{:id => "jean-pierre-kucheida",:name => "Jean-Pierre Kucheida"},
{:id => "jean-marc-ayrault",:name => "Jean-Marc Ayrault"},
{:id => "francois-hollande",:name => "François Hollande"},
{:id => "bernard-roman",:name => "Bernard Roman"},
{:id => "odette-duriez",:name => "Odette Duriez"},
{:id => "albert-facon",:name => "Albert Facon"},
{:id => "michel-lefait",:name => "Michel Lefait"},
{:id => "jerome-cahuzac",:name => "Jérôme Cahuzac"},
{:id => "laurent-fabius",:name => "Laurent Fabius"},
{:id => "jean-claude-perez",:name => "Jean-Claude Perez"},
{:id => "philippe-martin",:name => "Philippe Martin"},
{:id => "michel-sainte-marie",:name => "Michel Sainte-Marie"},
{:id => "francois-brottes",:name => "François Brottes"},
{:id => "pierre-bourguignon",:name => "Pierre Bourguignon"},
{},
{:id => "alain-neri",:name => "Alain Néri"},
{:id => "sylvie-andrieux",:name => "Sylvie Andrieux"},
{:id => "didier-mathus",:name => "Didier Mathus"},
{:id => "claude-bartolone",:name => "Claude Bartolone"},
{:id => "francois-loncle",:name => "François Loncle"},
{:id => "jean-claude-leroy",:name => "Jean-Claude Leroy"},
{:id => "bernard-derosier",:name => "Bernard Derosier"},
{},
{:id => "odile-saugues",:name => "Odile Saugues"},
{:id => "conchita-lacuey",:name => "Conchita Lacuey"},
{:id => "francoise-imbert",:name => "Françoise Imbert"},
{:id => "michel-delebarre",:name => "Michel Delebarre"},
{:id => "genevieve-gaillard",:name => "Geneviève Gaillard"},
{},
{:id => "pascale-crozon",:name => "Pascale Crozon"},
{:id => "philippe-vuilque",:name => "Philippe Vuilque"},
{:id => "laurent-cathala",:name => "Laurent Cathala"},
{:id => "jean-michel-boucheron",:name => "Jean-Michel Boucheron"},
{:id => "patrick-lemasle",:name => "Patrick Lemasle"},
{:id => "jean-louis-idiart",:name => "Jean-Louis Idiart"},
{:id => "pierre-cohen",:name => "Pierre Cohen"},
{:id => "michel-destot",:name => "Michel Destot"},
{:id => "henri-nayrou",:name => "Henri Nayrou"},
{},
{:id => "aurelie-filippetti",:name => "Aurélie Filippetti"},
{:id => "serge-blisko",:name => "Serge Blisko"},
{:id => "jerome-lambert",:name => "Jérôme Lambert"},
{:id => "pierre-alain-muet",:name => "Pierre-Alain Muet"},
{:id => "patrick-roy",:name => "Patrick Roy"},
{:id => "michel-liebgott",:name => "Michel Liebgott"},
{:id => "philippe-tourtelier",:name => "Philippe Tourtelier"},
{:id => "jean-claude-viollet",:name => "Jean-Claude Viollet"},
{:id => "rene-dosiere",:name => "René Dosière"},
{:id => "bernard-cazeneuve",:name => "Bernard Cazeneuve"},
{},
{:id => "jean-louis-dumont",:name => "Jean-Louis Dumont"},
{:id => "apeleto-albert-likuvalu",:name => "Apeleto Albert Likuvalu"},
{:id => "marietta-karamanli",:name => "Marietta Karamanli"},
{:id => "jean-louis-touraine",:name => "Jean-Louis Touraine"},
{:id => "jean-claude-fruteau",:name => "Jean-Claude Fruteau"},
{},
{},
{:id => "regis-juanico",:name => "Régis Juanico"},
{:id => "corinne-erhel",:name => "Corinne Erhel"},
{:id => "guillaume-garot",:name => "Guillaume Garot"},
{:id => "jean-michel-villaume",:name => "Jean-Michel Villaumé"},
{:id => "genevieve-fioraso",:name => "Geneviève Fioraso"},
{:id => "frederique-massat",:name => "Frédérique Massat"},
{:id => "marie-lou-marcel",:name => "Marie-Lou Marcel"},
{:id => "martine-martinel",:name => "Martine Martinel"},
{:id => "catherine-lemorton",:name => "Catherine Lemorton"},
{:id => "jacques-valax",:name => "Jacques Valax"},
{:id => "patrick-lebreton",:name => "Patrick Lebreton"},
{},
{:id => "andre-gerin",:name => "André Gerin"},
{:id => "jean-paul-lecoq",:name => "Jean-Paul Lecoq"},
{:id => "pierre-gosnat",:name => "Pierre Gosnat"},
{},
{:id => "marie-helene-amiable",:name => "Marie-Hélène Amiable"},
{:id => "jacques-desallangre",:name => "Jacques Desallangre"},
{:id => "jean-jacques-candelier",:name => "Jean-Jacques Candelier"},
{:id => "jean-pierre-brard",:name => "Jean-Pierre Brard"},
{:id => "roland-muzeau",:name => "Roland Muzeau"},
{:id => "patrick-braouezec",:name => "Patrick Braouezec"},
{:id => "francois-asensi",:name => "François Asensi"},
{:id => "jean-claude-sandrier",:name => "Jean-Claude Sandrier"},
{:id => "daniel-paul",:name => "Daniel Paul"},
{:id => "michel-vaxes",:name => "Michel Vaxès"},
{:id => "jacqueline-fraysse",:name => "Jacqueline Fraysse"},
{:id => "alfred-marie-jeanne",:name => "Alfred Marie-Jeanne"},
{:id => "alain-bocquet",:name => "Alain Bocquet"},
{:id => "marie-george-buffet",:name => "Marie-George Buffet"},
{:id => "andre-chassaigne",:name => "André Chassaigne"},
{:id => "maxime-gremetz",:name => "Maxime Gremetz"},
{:id => "noel-mamere",:name => "Noël Mamère"},
{:id => "huguette-bello",:name => "Huguette Bello"},
{},
{:id => "martine-billard",:name => "Martine Billard"},
{:id => "yves-cochet",:name => "Yves Cochet"},
{:id => "francois-de-rugy",:name => "François de Rugy"},
{:id => "marc-dolez",:name => "Marc Dolez"},
{:id => "anny-poursinoff",:name => "Anny Poursinoff"},
{:id => "michel-menard",:name => "Michel Ménard"},
{},
{:id => "christian-hutin",:name => "Christian Hutin"},
{:id => "gilbert-le-bris",:name => "Gilbert Le Bris"},
{},
{:id => "alain-rodet",:name => "Alain Rodet"},
{:id => "monique-boulestin",:name => "Monique Boulestin"},
{:id => "catherine-coutelle",:name => "Catherine Coutelle"},
{:id => "jean-michel-clement",:name => "Jean-Michel Clément"},
{},
{:id => "gerard-charasse",:name => "Gérard Charasse"},
{:id => "christiane-taubira",:name => "Christiane Taubira"},
{:id => "paul-giacobbi",:name => "Paul Giacobbi"},
{},
{:id => "chantal-robin-rodrigo",:name => "Chantal Robin-Rodrigo"},
{:id => "jeanny-marc",:name => "Jeanny Marc"},
{:id => "joel-giraud",:name => "Joël Giraud"},
{:id => "annick-girardin",:name => "Annick Girardin"},
{},
{:id => "guy-delcourt",:name => "Guy Delcourt"},
{:id => "jacqueline-maquet",:name => "Jacqueline Maquet"},
{:id => "alain-cacheux",:name => "Alain Cacheux"},
{:id => "dominique-baert",:name => "Dominique Baert"},
{:id => "jean-luc-perat",:name => "Jean-Luc Pérat"},
{:id => "sylvia-pinel",:name => "Sylvia Pinel"},
{:id => "chantal-berthelot",:name => "Chantal Berthelot"},
{:id => "dominique-orliac",:name => "Dominique Orliac"},
{},
{:id => "gilles-cocquempot",:name => "Gilles Cocquempot"},
{:id => "sandrine-hurel",:name => "Sandrine Hurel"},
{:id => "christophe-bouillon",:name => "Christophe Bouillon"},
{},
{:id => "valerie-fourneyron",:name => "Valérie Fourneyron"},
{:id => "gisele-biemouret",:name => "Gisèle Biémouret"},
{:id => "pascal-deguilhem",:name => "Pascal Deguilhem"},
{:id => "colette-langlade",:name => "Colette Langlade"},
{:id => "marie-noelle-battistel",:name => "Marie-Noëlle Battistel"},
{},
{:id => "martine-faure",:name => "Martine Faure"},
{:id => "philippe-plisson",:name => "Philippe Plisson"},
{:id => "laurence-dumont",:name => "Laurence Dumont"},
{:id => "herve-feron",:name => "Hervé Féron"},
{},
{},
{:id => "christian-eckert",:name => "Christian Eckert"},
{:id => "martine-pinville",:name => "Martine Pinville"},
{:id => "guy-chambefort",:name => "Guy Chambefort"},
]